services:
    caforum.sidebar.listener:
        class: caforum\sidebar\event\listener
        arguments:
            - '@config'
            - '@template'
            - '%core.root_path%'
        tags:
            - { name: event.listener }

